// Sample family tree data for the application
const SAMPLE_MEMBERS = [
  {
    id: "1",
    firstName: "Артур",
    lastName: "Альтхаус",
    maidenName: "",
    gender: "male",
    birthDate: "1910-04-12",
    birthPlace: "Гамбург, Германия",
    deathDate: "1995-08-20",
    deathPlace: "Санкт-Петербург, Россия",
    occupation: "Архитектор",
    bio: "Известный архитектор, переехавший в Санкт-Петербург в 1930-х годах. Участвовал в восстановлении исторических памятников после войны. Любил классическую музыку и коллекционировал старинные чертежи.",
    avatar: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "",
    motherId: "",
    spouses: [{ id: "2", marriageDate: "1935-06-15", marriagePlace: "Ленинград", divorced: false }]
  },
  {
    id: "2",
    firstName: "Мария",
    lastName: "Альтхаус",
    maidenName: "Волкова",
    gender: "female",
    birthDate: "1915-09-03",
    birthPlace: "Москва, Россия",
    deathDate: "2002-11-12",
    deathPlace: "Санкт-Петербург, Россия",
    occupation: "Врач-педиатр",
    bio: "Посвятила всю жизнь детской медицине. В военные годы работала в госпитале. Была душой семьи, организовывала традиционные воскресные обеды.",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "",
    motherId: "",
    spouses: [{ id: "1", marriageDate: "1935-06-15", marriagePlace: "Ленинград", divorced: false }]
  },
  {
    id: "3",
    firstName: "Елизавета",
    lastName: "Вэнс",
    maidenName: "Альтхаус",
    gender: "female",
    birthDate: "1938-11-22",
    birthPlace: "Ленинград, СССР",
    deathDate: "",
    deathPlace: "",
    occupation: "Пианистка, профессор консерватории",
    bio: "Окончила Ленинградскую консерваторию. Много лет преподавала фортепиано. Живет в Санкт-Петербурге, до сих пор дает частные уроки и пишет мемуары.",
    avatar: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "1",
    motherId: "2",
    spouses: [{ id: "6", marriageDate: "1960-08-12", marriagePlace: "Ленинград", divorced: false }]
  },
  {
    id: "4",
    firstName: "Николай",
    lastName: "Альтхаус",
    gender: "male",
    birthDate: "1942-05-18",
    birthPlace: "Ленинград, СССР",
    deathDate: "2018-03-05",
    deathPlace: "Владивосток, Россия",
    occupation: "Морской биолог",
    bio: "Исследователь глубин Тихого океана. Участвовал в десятках научных экспедиций. Автор нескольких книг о флоре и фауне Японского моря.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "1",
    motherId: "2",
    spouses: [{ id: "7", marriageDate: "1968-10-30", marriagePlace: "Владивосток", divorced: false }]
  },
  {
    id: "5",
    firstName: "Виктор",
    lastName: "Альтхаус",
    gender: "male",
    birthDate: "1948-07-07",
    birthPlace: "Ленинград, СССР",
    deathDate: "",
    deathPlace: "",
    occupation: "Художник-живописец",
    bio: "В 1970-х переехал во Францию. Его выставки проходят в Париже и Нью-Йорке. Пишет яркие импрессионистические пейзажи, часто вспоминая детство на Неве.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "1",
    motherId: "2",
    spouses: [{ id: "8", marriageDate: "1978-04-20", marriagePlace: "Париж", divorced: false }]
  },
  {
    id: "6",
    firstName: "Джордж",
    lastName: "Вэнс",
    gender: "male",
    birthDate: "1935-03-14",
    birthPlace: "Лондон, Великобритания",
    deathDate: "2010-09-02",
    deathPlace: "Санкт-Петербург, Россия",
    occupation: "Историк, переводчик",
    bio: "Английский ученый, влюбившийся в русскую литературу и Елизавету Альтхаус. Переехал в СССР в 1960 году. Переводил русскую классику на английский язык.",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "",
    motherId: "",
    spouses: [{ id: "3", marriageDate: "1960-08-12", marriagePlace: "Ленинград", divorced: false }]
  },
  {
    id: "7",
    firstName: "София",
    lastName: "Альтхаус",
    maidenName: "Ковалева",
    gender: "female",
    birthDate: "1945-02-28",
    birthPlace: "Новосибирск, СССР",
    deathDate: "",
    deathPlace: "",
    occupation: "Учитель русского языка и литературы",
    bio: "Преподавала в школе Владивостока более 40 лет. Заслуженный учитель РФ. Любит поэзию Серебряного века и походы в тайгу.",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "",
    motherId: "",
    spouses: [{ id: "4", marriageDate: "1968-10-30", marriagePlace: "Владивосток", divorced: false }]
  },
  {
    id: "8",
    firstName: "Хлоя",
    lastName: "Альтхаус",
    maidenName: "Дюбуа",
    gender: "female",
    birthDate: "1950-10-15",
    birthPlace: "Лион, Франция",
    deathDate: "",
    deathPlace: "",
    occupation: "Искусствовед, галерист",
    bio: "Встретила Виктора на выставке в Париже. Руководит галереей современного искусства на Монмартре.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "",
    motherId: "",
    spouses: [{ id: "5", marriageDate: "1978-04-20", marriagePlace: "Париж", divorced: false }]
  },
  {
    id: "9",
    firstName: "Артур",
    lastName: "Вэнс",
    gender: "male",
    birthDate: "1965-09-12",
    birthPlace: "Ленинград, СССР",
    deathDate: "",
    deathPlace: "",
    occupation: "Разработчик ПО, архитектор систем",
    bio: "Один из пионеров интернет-технологий в Санкт-Петербурге. Увлекается фотографией и парусным спортом.",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "6",
    motherId: "3",
    spouses: [{ id: "12", marriageDate: "1992-07-18", marriagePlace: "Санкт-Петербург", divorced: false }]
  },
  {
    id: "10",
    firstName: "Дмитрий",
    lastName: "Альтхаус",
    gender: "male",
    birthDate: "1970-02-14",
    birthPlace: "Владивосток, СССР",
    deathDate: "",
    deathPlace: "",
    occupation: "Предприниматель в сфере эко-туризма",
    bio: "Организует заповедные туры по Камчатке и Приморью. Ведет здоровый образ жизни, занимается дайвингом.",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "4",
    motherId: "7",
    spouses: [{ id: "13", marriageDate: "1998-09-05", marriagePlace: "Владивосток", divorced: false }]
  },
  {
    id: "11",
    firstName: "Анна",
    lastName: "Альтхаус",
    gender: "female",
    birthDate: "1975-08-01",
    birthPlace: "Владивосток, СССР",
    deathDate: "",
    deathPlace: "",
    occupation: "Писательница, журналист",
    bio: "Пишет детские приключенческие повести и научно-популярные статьи о природе Дальнего Востока. Много путешествует.",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "4",
    motherId: "7",
    spouses: [{ id: "14", marriageDate: "2002-05-15", marriagePlace: "Москва", divorced: true }]
  },
  {
    id: "12",
    firstName: "Елена",
    lastName: "Вэнс",
    maidenName: "Петрова",
    gender: "female",
    birthDate: "1967-05-30",
    birthPlace: "Псков, СССР",
    deathDate: "",
    deathPlace: "",
    occupation: "Ландшафтный дизайнер",
    bio: "Превращает городские пространства в зеленые оазисы. Проектировала сады для многих исторических усадеб Ленинградской области.",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "",
    motherId: "",
    spouses: [{ id: "9", marriageDate: "1992-07-18", marriagePlace: "Санкт-Петербург", divorced: false }]
  },
  {
    id: "13",
    firstName: "Юлия",
    lastName: "Альтхаус",
    maidenName: "Смирнова",
    gender: "female",
    birthDate: "1972-12-05",
    birthPlace: "Владивосток, СССР",
    deathDate: "",
    deathPlace: "",
    occupation: "Инструктор по йоге, диетолог",
    bio: "Увлекается восточной философией, аюрведой и здоровым питанием. Проводит семинары по медитации.",
    avatar: "https://images.unsplash.com/photo-1594744803329-e58b31de215f?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "",
    motherId: "",
    spouses: [{ id: "10", marriageDate: "1998-09-05", marriagePlace: "Владивосток", divorced: false }]
  },
  {
    id: "14",
    firstName: "Игорь",
    lastName: "Козлов",
    gender: "male",
    birthDate: "1973-11-10",
    birthPlace: "Хабаровск, СССР",
    deathDate: "",
    deathPlace: "",
    occupation: "Инженер-эколог",
    bio: "Занимается мониторингом состояния рек и лесов. Был женат на Анне Альтхаус, сохраняет с ней дружеские отношения ради дочери Ксении.",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "",
    motherId: "",
    spouses: [{ id: "11", marriageDate: "2002-05-15", marriagePlace: "Москва", divorced: true }]
  },
  {
    id: "15",
    firstName: "Алиса",
    lastName: "Вэнс",
    gender: "female",
    birthDate: "1995-06-25",
    birthPlace: "Санкт-Петербург, Россия",
    deathDate: "",
    deathPlace: "",
    occupation: "Графический дизайнер, иллюстратор",
    bio: "Работает в игровой студии, рисует концепт-арты. Любит аниме, велопрогулки и своего рыжего кота Арчи.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "9",
    motherId: "12",
    spouses: []
  },
  {
    id: "16",
    firstName: "Лев",
    lastName: "Вэнс",
    gender: "male",
    birthDate: "1998-10-09",
    birthPlace: "Санкт-Петербург, Россия",
    deathDate: "",
    deathPlace: "",
    occupation: "Студент-аспирант (физика)",
    bio: "Изучает квантовую оптику. Увлекается интеллектуальными играми, шахматами и играет на электрогитаре.",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "9",
    motherId: "12",
    spouses: []
  },
  {
    id: "17",
    firstName: "Максим",
    lastName: "Альтхаус",
    gender: "male",
    birthDate: "2000-01-20",
    birthPlace: "Владивосток, Россия",
    deathDate: "",
    deathPlace: "",
    occupation: "Спортсмен (парусный спорт)",
    bio: "Кандидат в мастера спорта. Мечтает обойти вокруг света на собственной яхте. Любит рок-музыку.",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "10",
    motherId: "13",
    spouses: []
  },
  {
    id: "18",
    firstName: "Ксения",
    lastName: "Козлова",
    gender: "female",
    birthDate: "2005-04-14",
    birthPlace: "Москва, Россия",
    deathDate: "",
    deathPlace: "",
    occupation: "Студентка (лингвистика)",
    bio: "Изучает китайский и японский языки. Увлекается фотографией и восточной культурой.",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "14",
    motherId: "11",
    spouses: []
  },
  {
    id: "19",
    firstName: "София",
    lastName: "Попова",
    gender: "female",
    birthDate: "1992-08-30",
    birthPlace: "Казань, Россия",
    deathDate: "",
    deathPlace: "",
    occupation: "Научный сотрудник (генетика)",
    bio: "Друг семьи Альтхаус. Занимается генетическим картированием. В данный момент не привязана к основному древу, но исследует его историю.",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150&q=80",
    fatherId: "",
    motherId: "",
    spouses: []
  }
];
window.SAMPLE_MEMBERS = SAMPLE_MEMBERS;
